<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Employee_select_BPM/BpmProject_insert/db_insert" name="db_insert_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../WSDLs/db_insert.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Employee_select_BPM/BpmProject_insert/db_insert"/>
    <wsdl:binding name="db_insert_ptt-binding" type="db:db_insert_ptt" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/Employee_select_BPM/BpmProject_insert/db_insert">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>