<wsdl:definitions
     name="db_insert"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Employee_select_BPM/BpmProject_insert/db_insert"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Employee_select_BPM/BpmProject_insert/db_insert"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_insert"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="db_insert_plt" >
    <plt:role name="db_insert_role" >
      <plt:portType name="tns:db_insert_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/db_insert" schemaLocation="../Schemas/db_insert_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmployeeInsertCollection_msg">
        <wsdl:part name="EmployeeInsertCollection" element="top:EmployeeInsertCollection"/>
    </wsdl:message>
    <wsdl:portType name="db_insert_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:EmployeeInsertCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
